### ISSUE TITLE
Drop Down Menu Styling

### ISSUE THREAD

**Issue by safaci2000** [OSAlt/gb-www-nixiepixel#18]
If we add something along these lines to the headers

```html
  <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      About
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="/#about">About Me</a>
                      <a class="dropdown-item" href="/nixie">Read My Story</a>
                    </div>
                </div>
```

The look/feel clashes with the theme.  Can we fix the SCSS to better fit the current style.

**Comment by kankurodev** [comment]
Do we even want a drop down? If I recall Nixie isn't a fan about dropdowns and I specifically made it so the menu works on all screen sizes.

Just don't see the point in making a dropdown when there are only 4 items.

**Comment by safaci2000** [comment]
You can have a drop down work on all screen sizes.  If we add more content it'd be nice not to have 20 menu items from left to right.

**Comment by kankurodev** [comment]
I don't think this is needed, especially not now. If we do add more in the future we can discuss it, but for now I'm not on board with the idea, bad for design the way it stands now.
